### ISSUE TITLE
Fix for new gcc version?

### ISSUE THREAD

**Issue by robots** [kjoehass/fxopt#1]
Hello,

It seems that gcc has changed the plugin model to C++, and there are some nontrivial changes necessary to make this project work again.

Are you planing to port it to new gcc? Is there some similar project available somewhere?

**Comment by kjoehass** [comment]
I'm afraid that I just started a new job and it will take some time before I have a development environment set up again. Is this a critical need for a particular project? I seem to recall that Altera was working on something similar but it was for LLVM instead of gcc...I think they had a paper in one of the ACM journals about two years ago.

---

On Sun, 9/6/15, Michal notifications@github.com wrote:

 Subject: [fxopt] Fix for new gcc version? (#1)
 To: "kjoehass/fxopt" fxopt@noreply.github.com
 Date: Sunday, September 6, 2015, 7:27 AM

 Hello,

 It seems that gcc has changed the plugin model to C++,
 and there are some nontrivial changes necessary to make this
 project work again.

 Are you planing to port it to new gcc? Is there some
 similar project available somewhere?

 —
 Reply to this email directly or view it on
 GitHub.

**Comment by robots** [comment]
Its not critical i wanted to try and compile codec2 (vocoder) for mcu without hardware floating point, this project seemes to be the key.

Maybe i will figure it out myself, how to rewrite it when i find free time :)
